### PR TITLE
Ft user roles

### PR DESCRIPTION
**Pull request by MutegekiHenry**
PR Checklist

# Add User roles, Admin decorator and protection

## Description

_This PR does the following_

- It adds new tables for roles, and user roles(to enable a user have multiple roles)
- It adds endpoints to perform C.R.U.D on roles and user_roles tables
- It adds an admin decorator to help protect admin specific endpoints
- It adds a command line utility for creating default roles(administrator and app_user) 
- It adds a command line utility for creating a super_admin since they don't signup as normal users
- It updates the readMe file to add instructions on how to create default roles and super_admin

## How to test this PR?

- Pull the branch locally and activate your virtual environment
- Upgrade your migrations to get the new roles tables `python manage.py db upgrade`
- Create default roles via command line by running `python manage.py create_roles`
- Create a super admin via command line by running `python manage.py admin_user --email=<an email> --password=<the password> --confirm_password=<the password>` replace content in <> with actual values.
- Run the app `flask run`
- Test the endpoints on roles and user roles (Note: to test these you need an admin token so sign in with admin account)

### CODE REVIEW

**Review by Schade9 — COMMENTED** [review]
Great work. I've even learnt more about decorators. Everything works fine.

**Review by Schade9 — COMMENTED** [review]
The code for creating a super user and default roles work fine.
The  migrations also work fine.

Issues. (When signed in as admin)
1. You cannot register an new user until you uncomment the fields in the __init__ method of the user model.
2. The endpoints for /roles give an error of `if not has_role(claims['roles'], 'administrator'):
KeyError: 'roles'` which comes from the decorators.py file
3. Creating a new role gives an error of `"msg": "Missing Authorization Header"`. This might be due to maybe some missing fields in the api_docs file
4. Basically all endpoints that are supposed to be accessed only by the super user give errors of bullet 2 or bullet 3.

Those are the errors that have to be rectified.

**Comment by MutegekiHenry** [comment]
> The code for creating a super user and default roles work fine. The migrations also work fine.
> 
> Issues. (When signed in as admin)
> 
> 1. You cannot register an new user until you uncomment the fields in the **init** method of the user model.
> 2. The endpoints for /roles give an error of `if not has_role(claims['roles'], 'administrator'): KeyError: 'roles'` which comes from the decorators.py file
> 3. Creating a new role gives an error of `"msg": "Missing Authorization Header"`. This might be due to maybe some missing fields in the api_docs file
> 4. Basically all endpoints that are supposed to be accessed only by the super user give errors of bullet 2 or bullet 3.
> 
> Those are the errors that have to be rectified.

Hi @Schade9 all these have been fixed in my newest commit. kindly retest.

**Comment by Schade9** [comment]
I cannot ask for anything more. :-) Great work

**Pull request merged**
